git:
  depth: false
  
# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0

install:
  - travis_retry composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then composer require --dev phpunit/phpunit ^5.0; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^7.0 ]]; then composer require --dev phpunit/phpunit ^7.0; fi
