git:
  depth: false
  
# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  
language: php

matrix:
  include:
    - php: 5.6

install:
  - travis_retry composer install
