git:
  depth: false
  
# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  
language: php

install:
  - travis_retry composer install
