Articulo:
   actAs: [Timestampable]
   tableName: blog_articulo
   columns:
      id:
         type: integer
         primary: true
         autoincrement: true
      titulo:   string(255)
      contenido: clob

Comentario:
   actAs: [Timestampable]
   tableName: blog_comentario
   columns:
      id:
         type: integer
         primary: true
         autoincrement: true
      articulo_id: integer
      autor: string(255)
      contenido: clob
      relations:
         Articulo:
            onDelete: CASCADE
            foreignAlias: Comentarios